Repository tendermint/tm-db, pull requests merged in 2020-05, with the labels that each got.

#92 ci: change linter
  .github/workflows/lint.yml
  .golangci.yml
  common_test.go
Labels: S:automerge

#93 README: add GoDoc badge
  README.md
Labels: C:docs

#94 DB: document that iterators must be closed
  types.go
Labels: C:docs, S:automerge

#95 godoc: emphasize read-only key/value slices, tweak interface docs
  backend_test.go
  memdb.go
  test_helpers.go
  types.go
  util.go
Labels: C:docs

#96 batch: return errors for all operations
  CHANGELOG.md
  backend_test.go
  boltdb_batch.go
  cleveldb_batch.go
  goleveldb_batch.go
  memdb_batch.go
  prefixdb_batch.go
  remotedb/batch.go
  remotedb/grpcdb/server.go
  remotedb/remotedb_test.go
  rocksdb_batch.go
  types.go
Labels: T:breaking

#97 iterator: improve and document error handling
  CHANGELOG.md
  boltdb_iterator.go
  cleveldb_iterator.go
  goleveldb_iterator.go
  memdb_iterator.go
  prefixdb_iterator.go
  remotedb/iterator.go
  remotedb/remotedb_test.go
  rocksdb_iterator.go
  types.go
Labels: T:breaking

#98 improve error handling
  CHANGELOG.md
  backend_test.go
  boltdb.go
  cleveldb_test.go
  common_test.go
  db.go
  go.mod
  go.sum
  memdb_batch.go
  remotedb/batch.go
  remotedb/grpcdb/server.go
  remotedb/remotedb.go
  rocksdb_test.go
Labels: S:automerge, T:breaking

#99 reject nil/empty keys and nil values
  CHANGELOG.md
  backend_test.go
  boltdb.go
  boltdb_batch.go
  boltdb_iterator.go
  cleveldb.go
  cleveldb_batch.go
  goleveldb.go
  goleveldb_batch.go
  memdb.go
  memdb_batch.go
  prefixdb.go
  prefixdb_batch.go
  prefixdb_iterator.go
  prefixdb_test.go
  rocksdb.go
  rocksdb_batch.go
  types.go
  util.go
Labels: T:breaking
